name: Run python script, generate resume, push to repo gh-pages

on:
  push:
    branches:
      - main
      - develop

jobs:
  generate-resume:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run python script
        run: |
          python src/main.py
      - name: Commit files
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout -b gh-pages
          git add dist/ index.html -f
          git commit -m "generated resume"
          git push --set-upstream origin gh-pages -f